"""empty message

Revision ID: 087d3afb4e8e
Revises: a005fc9e7cce
Create Date: 2020-12-16 10:00:58.680218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '087d3afb4e8e'
down_revision = 'a005fc9e7cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('computing_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'computing_id')
    # ### end Alembic commands ###
