"""empty message

Revision ID: 153f0c90cdfc
Revises: 087d3afb4e8e
Create Date: 2021-01-07 16:41:52.387889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '153f0c90cdfc'
down_revision = '087d3afb4e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('last_modified', sa.DateTime(), nullable=True))
    op.execute("UPDATE sample SET last_modified = date")
    op.alter_column('sample', 'last_modified', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'last_modified')
    # ### end Alembic commands ###
