"""empty message

Revision ID: 39a845579587
Revises: fa4b41e0bfe6
Create Date: 2020-09-23 15:50:44.987745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a845579587'
down_revision = 'fa4b41e0bfe6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ivy_file', sa.Column('sample_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ivy_file', 'sample_count')
    # ### end Alembic commands ###
