"""empty message

Revision ID: 872a6f0eb552
Revises: b6ac8e905ea9
Create Date: 2021-01-12 10:06:04.131192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872a6f0eb552'
down_revision = 'b6ac8e905ea9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deposit', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deposit', 'notes')
    # ### end Alembic commands ###
