"""empty message

Revision ID: 8a2bf0c948ec
Revises: 166ae4251208
Create Date: 2020-09-14 13:16:39.099811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a2bf0c948ec'
down_revision = '166ae4251208'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample',
    sa.Column('barcode', sa.String(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('location', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('result_code', sa.String(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('in_firebase', sa.Boolean(), nullable=True),
    sa.Column('in_ivy', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('barcode')
    )
    op.drop_table('contact')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='contact_pkey')
    )
    op.drop_table('sample')
    # ### end Alembic commands ###
