"""empty message

Revision ID: 98f1eed6de4d
Revises: 3525dcf128cb
Create Date: 2020-09-25 11:26:03.661365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98f1eed6de4d'
down_revision = '3525dcf128cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('firebase_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kiosk',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sample', sa.Column('kiosk_id', sa.Integer(), nullable=False))
    op.add_column('sample', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sample', 'location', ['location_id'], ['id'])
    op.create_foreign_key(None, 'sample', 'kiosk', ['kiosk_id'], ['id'])
    op.drop_column('sample', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('location', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_column('sample', 'location_id')
    op.drop_column('sample', 'kiosk_id')
    op.drop_table('kiosk')
    op.drop_table('location')
    # ### end Alembic commands ###
