"""empty message

Revision ID: a005fc9e7cce
Revises: 3525dcf128cb
Create Date: 2020-10-15 13:40:29.696495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a005fc9e7cce'
down_revision = '3525dcf128cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('ivy_file', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'ivy_file')
    # ### end Alembic commands ###
