"""empty message

Revision ID: a34e7a6a1e03
Revises: 087d3afb4e8e
Create Date: 2020-12-29 09:34:30.759118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a34e7a6a1e03'
down_revision = '087d3afb4e8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sample', sa.Column('station', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sample', 'station')
    # ### end Alembic commands ###
